name: Deploy Real Estate to GitHub Pages

on:
  push:
    paths:
      - 'projects/real-estate/**'  # Specify the path to the application folder
    branches:
      - main  # Change this to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build real estate
        run: npm run build real-estate --base-href=/real-estate/  # Adjust this as needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/real-estate  # Specify the build output directory
          publish_branch: gh-pages
          destination_dir: real-estate
